### ISSUE TITLE
Create EXE

### ISSUE THREAD

**Issue by reloxx13** [WoHinDu/Tasmota-Firmware-Updater#2]
Huhu,

mit pyinstaller kannst du bequem noch eine .exe datei erstellen die alle libs die dein python script beinhaltet mit dabei hat, macht es für die user noch einfacher da nichts zusätzlich installiert werden muss.

schau mal bei SonOTA dort habe ich auch eine .exe nachgereicht. Dort findest du auch noch die pyinstaller config die du auf dein project anpassen musst.

**Comment by WoHinDu** [comment]
Danke für den Tipp. Ich werde es mir nächste Woche mal anschauen.

**Comment by WoHinDu** [comment]
@reloxx13 Vielen Dank für den Tipp!

Ich habe soeben die erste .exe veröffentlicht. Diese ist hier zu finden: [Download](https://github.com/WoHinDu/Tasmota-Firmware-Updater/releases)
